version: '3'
services:
  db:
    image: "mysql:5.7"
    volumes:
      - ./uvdesk/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "uvdesk"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  uvdesk:
    image: nuttcorp/uvdesk:latest
    depends_on:
      - db
    tty: true
    environment:
        MYSQL_USER: "uvdesk"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_DATABASE: uvdesk
    ports:
        - 80:80

volumes:
  db_data: {}